<?php
echo $this->doctype();
$this->headMeta()->appendHttpEquiv('Content-Type', 'text/html; charset=UTF-8');
?>
<html>
<head>
<meta http-equiv="X-UA-Compatible" content="IE=edge" />
<?php
echo $this->headMeta();
echo $this->headTitle();
$cadena = $_SERVER['HTTP_USER_AGENT'];
$buscar = "MSIE";
$resultado = strpos($cadena, $buscar);
if($resultado !== FALSE){
    $buscar = "MSIE 9.0";
    $buscarb = "Trident/5.0";
    $resultado = strpos($cadena, $buscar);
    $resultadob = strpos($cadena, $buscarb);
    if($resultado === FALSE && $resultadob === FALSE){
        ?>
        <div style="margin: 100px auto; color: #AAA; width: 500px; padding: 25px; text-align: center; font-size: 16px; font-family: arial">
            <img src="/images/logobuenaventura.jpg" />
            <br /><br />
            Usted está usando una versión de navegador incompatible con el sistema, le recomendamos  
            <a href="http://windows.microsoft.com/es-es/internet-explorer/downloads/ie-9/worldwide-languages" title="Internet Explorer 9">
                actualizar</a> a la versión más reciente o prueba <a href="https://www.google.com/intl/es/chrome/browser/?hl=es" title="Google Chrome!">otro</a>.
        </div>
        <?php
        exit;
    }
}

echo $this->HeadScript();
echo $this->HeadLink(); 
?>
<link rel="stylesheet" href="/css/print.css" type="text/css" media="print" />
<!--[if lte IE 7]>
<style>
html, body{ height: auto; 
h3 { margin: 0px; padding: 0px; padding-top: 10px; font-size: 13px; }
form{ margin: 0px; padding: 0px; 
.toolbar{ width: auto; 
</style>
<![endif]-->
<!--[if IE 8]>
<style>
html, body{ height: auto; }
form{ margin: 0px; padding: 0px; 
.toolbar{ }
</style>
<![endif]-->
</head>
<body>
<!-- INICIO SECCIÓN DE IMPRESIÓN -->
<div id="divCabeceraPrint" style="display:none; border-bottom: 1px solid #000; margin-bottom: 20px; padding-bottom: 20px; width: 100%; height:60px">
<div style="float:left; width:50%; text-align:left"><img src="/images/logobuenaventura.jpg" /></div>
<div style="float:right; width:50%; text-align:right; padding-top:10px;"><br /><br /><br /><br />
<?php 
$mes = date("n"); 
$mesArray = array( 1 => "Enero", 2 => "Febrero", 3 => "Marzo", 4 => "Abril", 5 => "Mayo", 6 => "Junio", 
                   7 => "Julio", 8 => "Agosto", 9 => "Septiembre", 10 => "Octubre", 11 => "Noviembre", 
                   12 => "Diciembre" ); $semana = date("D"); 
$semanaArray = array( "Mon" => "Lunes", "Tue" => "Martes", "Wed" => "Miercoles", "Thu" => "Jueves", 
                      "Fri" => "Viernes", "Sat" => "Sábado", "Sun" => "Domingo", ); 
$mesReturn = $mesArray[$mes]; 
$semanaReturn = $semanaArray[$semana]; 
$dia = date("d"); $año = date ("Y"); 
echo $semanaReturn.", ".$dia." de ".$mesReturn." de ".$año; 
?></div>
</div>
<!-- FIN SECCIÓN DE IMPRESIÓN -->
<?php echo $this->layout()->content; ?>
<!--Desarrollado por <a href="http://www.cyberline.com.pe/" style="text-decoration:none; color:#777" target="_blank">Cyberline SRL</a>-->
</table>
</body>
</html>
